# Generated by Django 4.2.13 on 2026-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EndpointCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=200)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("is_up", models.BooleanField(default=False)),
                ("response_ms", models.IntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "endpoint_checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["name", "-checked_at"],
                        name="endpoint_ch_name_903501_idx",
                    )
                ],
            },
        ),
    ]
