# Generated by Django 6.0.4 on 2026-05-03 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('orders_fetched', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('shopify', 'Shopify'), ('quickbooks', 'QuickBooks')], max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('order_date', models.DateField()),
                ('channel', models.CharField(choices=[('DTC', 'Direct to Consumer'), ('wholesale', 'Wholesale')], max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order_date'],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_consumed_sq_yards', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
            ],
        ),
    ]
