# Generated by Django 6.0.5 on 2026-05-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('general_manager', 'General Manager'), ('warehouse_manager', 'Warehouse Manager'), ('sales_analyst', 'Sales Analyst'), ('viewer', 'Viewer'), ('custom', 'Custom')], default='viewer', max_length=30),
        ),
    ]
